### ISSUE TITLE
Wanted to correct this look of website rendering

### ISSUE THREAD

**Issue by eshan1925** [openAOD/Central#11]
![image](https://user-images.githubusercontent.com/78701779/150800295-a068cf69-f5a3-469d-a260-7ceea4e6ba4a.png)
![image](https://user-images.githubusercontent.com/78701779/150800325-48264e22-b896-4349-860b-9c6047c1be49.png)

As you can see because of a small problem of links the website is not rendering properly so please assign me this issue and I will try to style this page so that it looks perfect.

**Comment by eshan1925** [comment]
Hey @aryashah2k Please see if this is a valid issue and if I can contribute to this.

**Comment by aryashah2k** [comment]
@ChlorinePentoxide , what do you think? If required I will assign or do you have something else in mind which he can work on?

**Comment by eshan1925** [comment]
> @ChlorinePentoxide , what do you think? If required I will assign or do you have something else in mind which he can work on?

I wanted to correct this as it does not look good in my opinion, so you can assign me this issue and I will correct it and also apply some styling...
Thank you

**Comment by ChlorinePentoxide** [comment]
@eshan1925 Well, I am aware of this issue. This is due to the files not yet being created rather than a styling issue. For the new files to be created, the existing Fire tool must be modified. However, I am currently working on another modular build tool for this which will fix it eventually.
Since you mention styling, maybe you can work on the frontend aspect of the portal, when I first created these websites I had focused more on the functional part of it so I modified the default Docusaurus theme. See if you can come up with a theme for it. 
The relevant files are in Central repo, Sources/Portal don't change the directory structure as it is hardwired into the build machine.

**Comment by eshan1925** [comment]
> @eshan1925 Well, I am aware of this issue. This is due to the files not yet being created rather than a styling issue. For the new files to be created, the existing Fire tool must be modified. However, I am currently working on another modular build tool for this which will fix it eventually.
> Since you mention styling, maybe you can work on the frontend aspect of the portal, when I first created these websites I had focused more on the functional part of it so I modified the default Docusaurus theme. See if you can come up with a theme for it. 
> The relevant files are in Central repo, Sources/Portal don't change the directory structure as it is hardwired into the build machine.

@ChlorinePentoxide will try to do it...
Please assign me the issue😁
